# Generated by Django 5.2.5 on 2025-09-10 11:26

from django.db import migrations, connection
from django.conf import settings


def forwards_func(apps, schema_editor):
    """Only run pgvector setup on PostgreSQL"""
    if "postgresql" in settings.DATABASES["default"]["ENGINE"]:
        with connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


def reverse_func(apps, schema_editor):
    """Only drop extension on PostgreSQL"""
    if "postgresql" in settings.DATABASES["default"]["ENGINE"]:
        with connection.cursor() as cursor:
            cursor.execute("DROP EXTENSION IF EXISTS vector CASCADE;")


class Migration(migrations.Migration):
    dependencies = [
        ("content_access_control", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
