# Generated by Django 5.2.5 on 2025-09-11 10:09

import file_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_processing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgesource",
            name="file",
            field=models.FileField(upload_to=file_processing.models.upload_to),
        ),
    ]
