# Generated by Django 5.2.6 on 2025-09-22 18:40

import content_access_control.policy_mixins
import django.db.models.deletion
import file_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_processing", "0003_alter_knowledgesource_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("vector", file_processing.models.VectorField(null=True)),
                ("embedding_model", models.CharField(max_length=255)),
                (
                    "knowledge_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="file_processing.knowledgesource",
                    ),
                ),
            ],
            bases=(
                content_access_control.policy_mixins.ObjectIdentifierMixin,
                models.Model,
            ),
        ),
        migrations.DeleteModel(
            name="ChunkVector",
        ),
    ]
