# Generated by Django 5.2.6 on 2025-09-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_processing", "0004_queryvector_delete_chunkvector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryvector",
            name="file",
            field=models.FileField(max_length=255, upload_to=""),
        ),
    ]
