name: "Terraform"

on:
  workflow_run:
    workflows: ["Build and Push Docker image to GHCR"]
    types:
      - completed

# Add permissions for OIDC
permissions:
  contents: read
  id-token: write # Required for OIDC authentication to your cloud provider

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    # The 'production' environment is optional but good for protection rules
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "mcp-knowledge-server"
          workload_identity_provider: "projects/372502133685/locations/global/workloadIdentityPools/github/providers/github-actions"

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory
      # Terraform will automatically read the backend configuration from your .tf files
      - name: Terraform Init
        run: cd infrastructure && terraform init

      - name: Terraform Apply
        run: cd infrastructure && TF_VAR_docker_image_tag= ${{ github.sha}} terraform apply -auto-approve -var-file=./environments/deployed.tfvars
